In [1]:
import pandas as pd
pd.__version__

'1.0.5'

In [2]:
import numpy as np

# The Pandas Series object

In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
data[1]

0.5

In [8]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])

data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data['b']

0.5

In [4]:
population_dict = {'California': 38332521,
                  'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [5]:
population.values

array([38332521, 26448193, 19651127, 19552860, 12882135], dtype=int64)

In [12]:
population['California']

38332521

In [13]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [14]:
pd.Series([2,5,6])

0    2
1    5
2    6
dtype: int64

In [15]:
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [16]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [17]:
pd.Series({2:'a', 1:'b', 3: 'c'}, index = [3, 2])

3    c
2    a
dtype: object

# Dataframe

In [10]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [11]:
states = pd.DataFrame({'population':population, 'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [21]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [22]:
states.columns

Index(['population', 'area'], dtype='object')

In [23]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [12]:
states['area'].values

array([423967, 695662, 141297, 170312, 149995], dtype=int64)

In [24]:
#from a single Series object
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [25]:
# from a list of dicts

data = [{'a': i, 'b': 2 * i} for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [27]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [28]:
pd.DataFrame([{'a': 1, 'b': 2},{'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [29]:
#from a dicts of Series objects

pd.DataFrame({'population':population, 'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [31]:
# from two-dimensional NumPy array

pd.DataFrame(np.random.rand(3,2), columns=['foo','bar'], 
             index=['a','b','c'])

foo       bar
a  0.287818  0.628726
b  0.021132  0.971834
c  0.782736  0.378430

In [33]:
ind  = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [34]:
ind[1]

3

In [35]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [36]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [37]:
ind[1] = 0 #INDEX objects cannot be modified

TypeError: Index does not support mutable operations

In [38]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [39]:
indA & indB #intersection

Int64Index([3, 5, 7], dtype='int64')

In [40]:
indA | indB #union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [41]:
indA ^ indB #symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

# Data Indexing and Selection

In [13]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c', 'd'])

In [14]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [43]:
data['b']

0.5

In [44]:
'a' in data

True

In [45]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [46]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [47]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [48]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [49]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [50]:
data[(data>0.3) & (data<0.8)]

b    0.50
c    0.75
dtype: float64

In [51]:
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [52]:
data = pd.Series(['a', 'b', 'c'], index = [1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [53]:
# explicit index
data[1]

'a'

In [54]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [55]:
# refer to explicit indexing
data.loc[1]

'a'

In [56]:
data.loc[1:3]

1    a
3    b
dtype: object

In [57]:
# refer to implicit indexing
data.iloc[1]

'b'

In [58]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [59]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop': pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [60]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [61]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [62]:
data.area is data['area']

True

In [64]:
data['densit'] = data['pop']/data['area']
data

area       pop      densit
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [65]:
data.T

California         Texas      New York       Florida      Illinois
area    4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop     3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
densit  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [67]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [68]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [69]:
data.ix[:3,'pop']

C:\Users\muhos601\Anaconda3\envs\dml\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Users\muhos601\Anaconda3\envs\dml\lib\site-packages\pandas\core\indexing.py:961: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  return getattr(section, self.name)[new_key]


California    38332521
Texas         26448193
New York      19651127
Name: pop, dtype: int64

In [70]:
data.loc[data['densit'] > 100, ['pop', 'densit']]

pop      densit
New York  19651127  139.076746
Florida   19552860  114.806121

In [71]:
data.iloc[0, 2] = 90
data

area       pop      densit
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [73]:
data.iloc[1:3] #direct indexing referes to rows

area       pop      densit
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [4]:
student_pop = pd.Series({'UU':5000, 'KTH': 5500, 'Chalmers': 4100})
start_date = pd.Series({'UU':1600, 'KTH': 1850, 'Chalmers': 2000})
data = pd.DataFrame({'Student pop':student_pop, 'Start date': start_date})
data

Student pop  Start date
UU               5000        1600
KTH              5500        1850
Chalmers         4100        2000

In [6]:
data.values

array([[5000, 1600],
       [5500, 1850],
       [4100, 2000]], dtype=int64)

In [7]:
data.columns

Index(['Student pop', 'Start date'], dtype='object')

In [8]:
data.index

Index(['UU', 'KTH', 'Chalmers'], dtype='object')

In [9]:
data['Start date']

UU          1600
KTH         1850
Chalmers    2000
Name: Start date, dtype: int64

In [11]:
data.iloc[1]

Student pop    5500
Start date     1850
Name: KTH, dtype: int64

In [12]:
data.loc['Chalmers','Student pop']

4100

In [13]:
data.iloc[:2,:]

Student pop  Start date
UU          5000        1600
KTH         5500        1850

In [16]:
data[data['Student pop']<4500]

Student pop  Start date
Chalmers         4100        2000

In [25]:
data.stack()

UU        Student pop    5000
          Start date     1600
KTH       Student pop    5500
          Start date     1850
Chalmers  Student pop    4100
          Start date     2000
dtype: int64

In [27]:
s1 = pd.Series({'a':1, 'b':2})
s2 = pd.Series({'c':3, 'd':4})
s1.add(s2, fill_value=0)

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64

In [34]:
data.iloc[0,0] = None
data.iloc[2,1] = None
data.iloc[0,1] = None

In [35]:
data.isnull()

Student pop  Start date
UU               True        True
KTH             False       False
Chalmers        False        True

In [36]:
data[data.notnull()]

Student pop  Start date
UU                NaN         NaN
KTH            5500.0      1850.0
Chalmers       4100.0         NaN

In [37]:
data.dropna()

Student pop  Start date
KTH       5500.0      1850.0

In [38]:
data.dropna(axis='columns')

Empty DataFrame
Columns: []
Index: [UU, KTH, Chalmers]

In [39]:
data.dropna(how='all')

Student pop  Start date
KTH            5500.0      1850.0
Chalmers       4100.0         NaN

# Operating on data in Pandas

In [74]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [75]:
df = pd.DataFrame(rng.randint(0,10, (3,4)), columns = ['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [76]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [77]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

# Index alignment 

In [78]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [79]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [80]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [81]:
A = pd.Series([2, 4, 6], index = [0, 1, 2])
B = pd.Series([1, 3, 4], index = [1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [82]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    4.0
dtype: float64

In [83]:
A = pd.DataFrame(rng.randint(0, 20, (2,2)), columns = list('AB'))
A

A   B
0  1  11
1  5   1

In [84]:
B = pd.DataFrame(rng.randint(0, 10, (3,3)), columns = list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [85]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [89]:
A = rng.randint(10, size = (3,4))
df = pd.DataFrame(A, columns = list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [90]:
df.sub(df['R'], axis = 0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [1]:
import numpy as np
import pandas as pd

In [3]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [4]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [5]:
1 + np.nan

nan

In [6]:
0 * np.nan

nan

In [8]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [9]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [10]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [12]:
x = pd.Series(range(2), index = ['a', 'b'], dtype=int)
x


a    0
b    1
dtype: int32

In [14]:
x.loc['a'] = None 
x

a    NaN
b    1.0
dtype: float64

# Handling missing data 

In [15]:
data = pd.Series([1, np.nan, 'hello', None])

In [16]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [17]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [18]:
data.dropna()

0        1
2    hello
dtype: object

In [19]:
df = pd.DataFrame([[1, np.nan, 2], [2, 3, 5], [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [21]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [22]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [24]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [25]:
df.dropna(axis = 'columns', how = 'all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [7]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [11]:
np.random.randint(0,10,(4,2))

array([[5, 7],
       [2, 9],
       [0, 4],
       [3, 4]])

# MultiIndex

In [12]:
df = pd.DataFrame(np.random.randint(0,10,(4,2)), index=[['a','a','b','b'],[1, 2, 1, 2]],
                 columns=['data1','data2'])
df

data1  data2
a 1      7      8
  2      8      4
b 1      8      7
  2      4      5

In [3]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop


(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [4]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [7]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [9]:
pop.loc['California',:]

California  2000    33871648
            2010    37253956
dtype: int64

In [10]:
pop.loc[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [11]:
pop.loc['New York', 2000]

18976457

In [14]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [21]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [22]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [25]:
f_u18 = pop_df['under18']/pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [17]:
ser = df.stack()
ser

a  1  data1    7
      data2    8
   2  data1    8
      data2    4
b  1  data1    8
      data2    7
   2  data1    4
      data2    5
dtype: int32

In [16]:
ser[:,:,'data1']

a  1    7
   2    8
b  1    8
   2    4
dtype: int32

In [13]:
pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [18]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [20]:
pd.MultiIndex.from_product([['a','b'],[1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [26]:
index = pd.MultiIndex.from_product([[2013, 2014],[1, 2]], names=['year',
                                                                'visit'])
columns = pd.MultiIndex.from_product([['Bod','Guido','Sue'],['HR','Temp']],
                                    names=['Subject','type'])
#mock some data
data = np.round(np.random.randn(4,6),1)
data[:,::2] *= 10
data +=37

#create the dataframe
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

Subject      Bod       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.0  35.8  55.0  37.8  39.0  37.3
     2      46.0  37.7  47.0  36.2  24.0  38.7
2014 1      25.0  36.4  42.0  38.1  39.0  37.4
     2      34.0  37.3  39.0  36.9  22.0  36.4

In [27]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      16.0  36.1
     2      20.0  36.9
2014 1      47.0  37.4
     2      28.0  36.9

In [31]:
health_data[['Guido','Bod']]

Subject    Guido         Bod      
type          HR  Temp    HR  Temp
year visit                        
2013 1      55.0  37.8  36.0  35.8
     2      47.0  36.2  46.0  37.7
2014 1      42.0  38.1  25.0  36.4
     2      39.0  36.9  34.0  37.3

# Indexing and slicing a multiIndex

In [74]:
index = pd.MultiIndex.from_tuples([('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)], names=['States', 'Year'])
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

pop = pd.Series(populations, index=index)
pop

States      Year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [31]:
pop['California', 2000]

33871648

In [32]:
pop['California']

2000    33871648
2010    37253956
dtype: int64

In [33]:
pop[:, 2000]

California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [36]:
pop[pop>22000000]

States      Year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [37]:
pop[['California','Texas']]

States      Year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

In [75]:
pop

States      Year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [76]:
pop_flat = pop.reset_index(name='population')
pop_flat

States  Year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [77]:
pop_flat.set_index(['States', 'Year'])

population
States     Year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [38]:
health_data

Subject      Bod       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      14.0  36.5  16.0  36.1  47.0  35.3
     2      50.0  36.7  20.0  36.9  33.0  36.4
2014 1      35.0  37.2  47.0  37.4  24.0  35.5
     2      47.0  36.1  28.0  36.9  36.0  36.1

In [39]:
health_data['Guido','HR']

year  visit
2013  1        16.0
      2        20.0
2014  1        47.0
      2        28.0
Name: (Guido, HR), dtype: float64

In [39]:
health_data.loc[2013, 'Bod']

type     HR  Temp
visit            
1      36.0  35.8
2      46.0  37.7

In [40]:
idx = pd.IndexSlice
health_data.loc[idx[2013,:],idx[:, 'Temp']]

Subject      Bod Guido   Sue
type        Temp  Temp  Temp
year visit                  
2013 1      35.8  37.8  37.3
     2      37.7  36.2  38.7

In [46]:
index = pd.MultiIndex.from_product([['UU', 'KTH', 'Lund'],
                                   [2019,2020]], names=['Uni', 'Year'])
nos_students = [1000,1500,1400, 1450, 800, 950]
stud = pd.Series(nos_students, index=index)
stud

Uni   Year
UU    2019    1000
      2020    1500
KTH   2019    1400
      2020    1450
Lund  2019     800
      2020     950
dtype: int64

In [48]:
stud['KTH', :]

Year
2019    1400
2020    1450
dtype: int64

In [49]:
stud_df = stud.unstack()
stud_df

Year  2019  2020
Uni             
KTH   1400  1450
Lund   800   950
UU    1000  1500

In [53]:
stud_df.mean(axis='columns')

Uni
KTH     1425.0
Lund     875.0
UU      1250.0
dtype: float64

In [61]:
index = pd.MultiIndex.from_product([['A', 'B'],[1,2,3],['x', 'y']],
                                   names=['l1','l2','l3'])
columns = pd.MultiIndex.from_product([['C','D', 'E'],[4,5],['r', 's']], 
                                    names=['L1','L2','L3'])
data = np.random.normal(0,1,(12,12))
df = pd.DataFrame(data, index = index, columns = columns)


In [68]:
idx = pd.IndexSlice
idx

In [73]:
df.loc[idx['A',:,:],idx[:,:,'s']]

L1               C                   D                   E          
L2               4         5         4         5         4         5
L3               s         s         s         s         s         s
l1 l2 l3                                                            
A  1  x  -0.165871  0.331379 -1.027727  1.807435 -0.542513 -0.447047
      y   0.168335  0.772126  0.597764 -0.609481  1.055531  0.379655
   2  x  -1.491002 -0.697293 -1.649089 -0.865918 -0.216432 -0.461484
      y  -0.510436 -1.299978  0.435077  0.292183 -1.224483  1.547159
   3  x  -0.891054 -0.885013  0.267432  0.536340  2.021508 -0.160143
      y   2.186213 -1.373833  0.035346  0.569386 -1.520684 -0.661687

In [40]:
health_data.iloc[:2,:2]

Subject      Bod      
type          HR  Temp
year visit            
2013 1      14.0  36.5
     2      50.0  36.7

In [41]:
health_data.mean(level='year')

Subject   Bod        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     32.0  36.60  18.0  36.50  40.0  35.85
2014     41.0  36.65  37.5  37.15  30.0  35.80